"""Add rows table

Revision ID: 3268c3cae5ca
Revises: 2acec45445a9
Create Date: 2021-05-14 22:17:46.144546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3268c3cae5ca'
down_revision = '2acec45445a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rows', sa.Column('title', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_rows_title'), 'rows', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rows_title'), table_name='rows')
    op.drop_column('rows', 'title')
    # ### end Alembic commands ###
