"""empty message

Revision ID: 879da1da3153
Revises: 
Create Date: 2021-12-14 16:20:34.656949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879da1da3153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rows_date'), 'rows', ['date'], unique=False)
    op.create_index(op.f('ix_rows_id'), 'rows', ['id'], unique=False)
    op.create_index(op.f('ix_rows_title'), 'rows', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rows_title'), table_name='rows')
    op.drop_index(op.f('ix_rows_id'), table_name='rows')
    op.drop_index(op.f('ix_rows_date'), table_name='rows')
    op.drop_table('rows')
    # ### end Alembic commands ###
